language: python

python:
  - "2.7"
  - "3.6"

addons:
  postgresql: "9.4"

services:
    - postgresql

install:
    - pip install -r requirements.txt

env:
  global:
    - TRAVIS_BUILD=true

before_script:
    - psql -c 'create database mitmi;' -U postgres

script:
    - coverage run --append manage.py test && coverage report -i
