language: python

python:
  - "2.7"
  - "3.6"

addons:
  postgresql: "9.6"

services:
    - postgresql

install:
    - pip install -r requirements.txt

env:
  global:
    - TRAVIS_BUILD=true

script:
    - coverage run --append manage.py test && coverage report -i
