"""empty message

Revision ID: c9839c0f0b1a
Revises: db399910d932
Create Date: 2017-03-04 18:58:17.895225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9839c0f0b1a'
down_revision = 'db399910d932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'created_by')
    # ### end Alembic commands ###
