"""empty message

Revision ID: db399910d932
Revises: 12b81447deac
Create Date: 2017-03-04 17:10:40.076379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db399910d932'
down_revision = '12b81447deac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'max_guests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('max_guests', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
